scripts: Hack around broken CentOS 8 Stream container repositories
The repositories in the container image container bit-rotted URLs that
needed to be updated to point to vault.centos.org.  This avoids:

  CentOS Stream 8 - AppStream                      42  B/s |  38  B     00:00
  Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

Signed-off-by: Martin Schwenke <mschwenke@ddn.com>
Change-Id: I175368b46119da821dc9ba59bb433f32f4f85700